# Library of Primary Accident Cause Codes
primary_accident_cause_codes = {
    "T001": "Roadbed settled or soft",
    "T002": "Washout/rain/slide/flood/snow/ice damage to track",
    "T099": "Other roadbed defects",
    "T101": "Cross level of track irregular (at joints)",
    "T102": "Cross level of track irregular (not at joints)",
    "T103": "Deviation from uniform top of rail profile",
    "T104": "Disturbed ballast section",
    "T105": "Insufficient ballast section",
    "T106": "Superelevation improper, excessive, or insufficient",
    "T107": "Superelevation runoff improper",
    "T108": "Track alignment irregular (other than buckled/sunkink)",
    "T109": "Track alighment irregular (buckled/sunkink)",
    "T110": "Wide gage (de to defective or missing crossties)",
    "T111": "Wide gage (due to defective or missing spikes or other rail fasteners)",
    "T112": "Wide gage (due to loose, broken, or defective gage rods)",
    "T113": "Wide gage (due to worn rails)",
    "T199": "Other track geometry defects",
    "T201": "Broken Rail - Bolt hole crack or break",
    "T202": "Broken Rail - Base",
    "T203": "Broken Rail - Weld (plant)",
    "T204": "Broken Rail - Weld (field)",
    "T205": "Defective or missing crossties (use code T110 if results in wide gage)",
    "T206": "Defective spikes or missing spikes or other rail fasteners (use code T111 if results in wide gage)",
    "T207": "Broken Rail - Detail fracture from shelling or head check",
    "T208": "Broken Rail - Engine burn fracture",
    "T210": "Broken Rail - Head and web separation (outside joint bar limits)",
    "T299": "Other rail and joint bar defects (Provide detailed description in narrative)",
    "T301": "Derail, defective",
    "T302": "Expansion joint failed or malfunctioned",
    "T303": "Guard rail loose/broken or mislocated",
    "T304": "Railroad crossing frog, worn or broken",
    "T305": "Retarder worn, broken, or malfunctioning",
    "T306": "Retarder yard skate defective",
    "T307": "Spring/power switch mechanism malfunction",
    "T308": "Stock rail worn, broken or disconnected",
    "T309": "Switch (hand operated) stand mechanism broken, loose, or worn",
    "T310": "Switch connecting or operating rod is broken or defective",
    "T311": "Switch damaged or out of adjustment",
    "T312": "Switch lug/crank broken",
    "T313": "Switch out of adjustment because of insufficient rail anchoring",
    "T314": "Switch point worn or broken",
    "T315": "Switch rod worn, bent, broken, or disconnected",
    "T316": "Turnout frog (rigid) worn, or broken",
    "T317": "Turnout frog (self guarded), worn or broken",
    "T318": "Turnout frog (spring) worn, or broken",
    "T319": "Switch point gapped (between switch point and stock rail)",
    "T399": "Other frog, switch and track appliance defects (Provide detailed description in narrative)",
    "T401": "Bridge misalignment or failure",
    "T402": "Flangeway clogged",
    "T403": "Engineering design or construction",
    "T404": "Catenary system defect",
    "T499": "Other way and structure defect (Provide detailed description in narrative)",
}

